parameters:
    error-codes-en:
        INTERNAL_SERVER_ERROR:
            code: 500
            msg: "INTERNAL SERVER ERROR"
        PRESENTATION_NOT_EXIST:
            code: 1
            msg: "Pesentation not exist"
        PARAMETER_NOT_PROVIDED:
            code: 2
            msg: "Parameter %s not valid"